### ISSUE TITLE
Compile error on Raspbian [JIRA: RIAK-1830]

### ISSUE THREAD

**Issue by randysecrist** [basho/eleveldb#106]
On a slightly older version of Raspbian (debian based linux), I see this compiler error during build:

``` bash
Compiling /home/pi/dev/rinamo/deps/eleveldb/c_src/eleveldb.cc
/home/pi/dev/rinamo/deps/eleveldb/c_src/eleveldb.cc: In function ‘ERL_NIF_TERM parse_init_option(ErlNifEnv*, ERL_NIF_TERM, EleveldbOptions&)’:
/home/pi/dev/rinamo/deps/eleveldb/c_src/eleveldb.cc:242:58: error: invalid conversion from ‘size_t* {aka unsigned int*}’ to ‘long unsigned int*’ [-fpermissive]
/home/pi/.erln8.d/otps/R16B02/dist/lib/erlang/erts-5.10.3/include/erl_nif_api_funcs.h:43:1: error:   initializing argument 3 of ‘int enif_get_ulong(ErlNifEnv*, ERL_NIF_TERM, long unsigned int*)’ [-fpermissive]
/home/pi/dev/rinamo/deps/eleveldb/c_src/eleveldb.cc: In function ‘ERL_NIF_TERM parse_open_option(ErlNifEnv*, ERL_NIF_TERM, leveldb::Options&)’:
/home/pi/dev/rinamo/deps/eleveldb/c_src/eleveldb.cc:330:58: error: invalid conversion from ‘size_t* {aka unsigned int*}’ to ‘long unsigned int*’ [-fpermissive]
/home/pi/.erln8.d/otps/R16B02/dist/lib/erlang/erts-5.10.3/include/erl_nif_api_funcs.h:43:1: error:   initializing argument 3 of ‘int enif_get_ulong(ErlNifEnv*, ERL_NIF_TERM, long unsigned int*)’ [-fpermissive]
/home/pi/dev/rinamo/deps/eleveldb/c_src/eleveldb.cc: In function ‘ERL_NIF_TERM eleveldb::async_open(ErlNifEnv*, int, const ERL_NIF_TERM*)’:
/home/pi/dev/rinamo/deps/eleveldb/c_src/eleveldb.cc:556:25: warning: integer overflow in expression [-Woverflow]
ERROR: compile failed while processing /home/pi/dev/rinamo/deps/eleveldb: rebar_abort
make: *** [compile] Error 1
```

Anyone know of a possible work around?

**Comment by matthewvon** [comment]
is this a 32 bit compiler versus 64 bit compiler?  I am guessing your size_t is 32 bits and long unsigned int is 64bit.   Yeah, that "integer overflow" in list 556 really seems to scream word size.

**Comment by randysecrist** [comment]
I am using a 32 bit erlang; trying to get 64 bit to compile under Raspbian - taking forever

**Comment by randysecrist** [comment]
no bueno for 64 bit on the pi

**Comment by matthewvon** [comment]
I polled my colleagues.  We do not have direct experience with Raspbian.  It was suggested that you might find help via https://twitter.com/TomTowny .  He is reported to be building Riak clusters on raspberry pi.

**Comment by bkerley** [comment]
Yeah, the Pi is a single board computer that was $25 two years ago, it's 32-bit ARM and about as fast as you'd expect a $25 computer with a 32-bit ARM from two years ago to be.

**Comment by randysecrist** [comment]
i was able to fix a few compilation issues by switching from size_t to unsigned long; however tests still fail with 'undefined symbols for __sync_sub_and_fetch_8'

**Comment by matthewvon** [comment]
Randy,

Basho has been tuning and augmenting eleveldb/leveldb with x86_64 servers in mind.  I fear you are going to continue to find 64 bit  and advanced gcc constructs in your way.

It occurs to me that Riak's interface has not changed since 1.2.  Your life would likely get a ton easier if you pulled the 1.2 versions/tags of eleveldb and leveldb from the respective basho repositories.

Matthew

**Comment by randysecrist** [comment]
Yep, understand.  I started pulling in older versions last night; almost made it to 1.3 before I fell asleep watching level compile.  1.2 is a good suggestion; thanks.

**Comment by randysecrist** [comment]
It may also be a good idea to configure off eleveldb somehow; I actually don't need it at all w/ the Riak I want to run.

**Comment by itsavvy-ankur** [comment]
Hi, looking to get some assistance myself around a similar issue while trying to build RIAK from source. Having resolved most of the issues i am now stuck with the below errors during 'make rel'

home/ankur/riak/deps/eleveldb/c_src/eleveldb.cc:332:58: error: invalid conversion from ‘size_t\* {aka unsigned int_}’ to ‘long unsigned int_’ [-fpermissive]
             if (enif_get_ulong(env, option[1], &memory_sz))

and 

In file included from c_src/eleveldb.h:27:0,
                 from /home/ankur/riak/deps/eleveldb/c_src/eleveldb.cc:35:
/usr/lib/erlang/erts-5.10.2/include/erl_nif_api_funcs.h:43:27: error:   initializing argument 3 of ‘int enif_get_ulong(ErlNifEnv_, ERL_NIF_TERM, long unsigned int_)’ [-fpermissive]
 ERL_NIF_API_FUNC_DECL(int,enif_get_ulong,(ErlNifEnv_, ERL_NIF_TERM term, unsigned long_ ip));

ERROR: compile failed while processing /home/ankur/riak/deps/eleveldb: rebar_abort

Can you please assist me in the right direction. I have a very limited understanding of what I am doing(just following instructions from the net).

**Comment by randysecrist** [comment]
The issue is that later versions of Basho's eleveldb has some code that is not compatible with ARM.  I am considering putting together a branch of Riak that relies on older eleveldb instead, but haven't gotten around to it.

Like it mentions above, there are prior tags which do work.

**Comment by itsavvy-ankur** [comment]
Thank you. Switching to 1.1.0 eleveldb resolved the issue. Stuck on a different problem now during rebar generate, may be I will report a separate issue.

**Comment by slfritchie** [comment]
Is this issue resolved enough to close?

**Comment by randysecrist** [comment]
I don't see a change, so no.

**Comment by matthewvon** [comment]
Basho is not supporting Raspbian.  An independent branch for Raspbian is welcome.  But the team decision was to not spend time on 32 bit support, hence the first closing of this issue.  Closing it again for same reason.

**Comment by randysecrist** [comment]
prob fine,  2.1+ we'll have to break out level to be more modular and not block Riak like how it does today.

**Comment by matthewvon** [comment]
What?  "not block Riak"?

**Comment by ixmatus** [comment]
More knowledge for posterity:

I ran into this issue as well because I'm building a complicated application in Erlang for an ARMv5 which is 32bit. I'm not using Riak specifically but we are using `riak_ensemble` which uses `leveldb` and `eleveldb`.

At first I attempted to solve the compiler warnings, which did indeed build everything correctly but when I cross-compiled all of the leveldb tests and put them on the ARM environment and ran them, about half failed with a segfault.

So, I instead built vanilla Google LevelDB at version **1.18**. It required some minor custom fiddling of the leveldb build scripts so I could build for a generic cross-compile Linux ARM environment but everything went well. Building the tests and running them on the ARM also succeeded with no segfaults.

I then also proceeded to modify `eleveldb` version **1.1.1** to support cross-compilation of itself, Snappy, and the new leveldb version.

NOTE: https://github.com/plumlife has quite a few forked repos that deal with the ARM32 support.

So far, everything is pretty happy - I hope someone finds this knowledge useful or it saves someone time.

**Comment by matthewvon** [comment]
I would make a wild guess that the gcc atomic operations used in Basho’s leveldb are causing issues for the ARM.  There are various Internet write-ups concerning gcc versions and such required for ARM atomics.  Of course, I am not sure why the code would even compile if the target version did not support the atomic operations used.  Hence, why this is just a wild guess.

The atomic operations are primarily in the threading code that supports multiple, simultaneous compactions.  I doubt you need that for the Raspbian.  Google’s original code should be satisfactory.

Matthew

**Comment by ixmatus** [comment]
@matthewvon I suspect you're right; why it compiles without errors or warnings also surprises me. I did not know Basho's leveldb fork uses libatomic; I wonder if GCC attempts to fallback to sync with semantics that don't quite work due to being built specifically for use with atomic?

We're not on the Raspbian but vanilla LevelDB has, so far, been working great. Our product also doesn't require the kind of performance most typical uses of Riak need.

**Comment by NoKriK** [comment]
Hi,

I was tring to run Riak on [Scaleway](https://scaleway.com) and hit the same compilation issue.
Is there a good workaround?
I tried to checkout eleveldb 1.2.2 and 1.1.1 but it then failed with the following message:

```
Compiling /root/riak/deps/eleveldb/src/eleveldb.erl failed:
/root/riak/deps/eleveldb/src/eleveldb.erl:93: opaque type db_ref() is not exported
/root/riak/deps/eleveldb/src/eleveldb.erl:95: opaque type itr_ref() is not exported
ERROR: compile failed while processing /root/riak/deps/eleveldb: rebar_abort
```

Is there a known solution?

**Comment by matthewvon** [comment]
You are compiling really old versions of Riak.  Erlang R15 or R14 was the compiler used back then.  Maybe you need the older version.  Just guessing.

**Comment by NoKriK** [comment]
Hi @matthewvon,

Thanks for your feedback.
I was able to go further by applying @ixmatus patch found [here](https://github.com/plumlife/eleveldb/commit/8d49e3738f304ddc612b751cd0df87d4cb163987).
The patch is also present in the current tree of eleveldb.

Now, everything is compiling but I'm stuck at the generate step of the riak build:

```
./rebar generate
==> rel (generate)
ERROR: Unexpected error: {'EXIT',
                             {{badmatch,{error,enoent}},
                              [{rebar_reltool,execute_overlay,4,
                                   [{file,"src/rebar_reltool.erl"},
                                    {line,388}]},
                               {rebar_reltool,generate,2,
                                   [{file,"src/rebar_reltool.erl"},{line,60}]},
                               {rebar_core,run_modules,4,
                                   [{file,"src/rebar_core.erl"},{line,491}]},
                               {rebar_core,execute,6,
                                   [{file,"src/rebar_core.erl"},{line,416}]},
                               {rebar_core,maybe_execute,8,
                                   [{file,"src/rebar_core.erl"},{line,300}]},
                               {rebar_core,process_dir1,7,
                                   [{file,"src/rebar_core.erl"},{line,259}]},
                               {rebar_core,process_each,5,
                                   [{file,"src/rebar_core.erl"},{line,349}]},
                               {rebar_core,process_dir1,7,
                                   [{file,"src/rebar_core.erl"},
                                    {line,251}]}]}}
ERROR: generate failed while processing /root/riak/rel: rebar_abort
Makefile:34: recipe for target 'generate' failed
make: *** [generate] Error 1
```

I believe I hit the following issue which is marked as solved but isn't really: https://github.com/basho/riak/issues/551

I'm going to continue there.

**Comment by NoKriK** [comment]
The issue at the relbar generate step is due to missing configuration template files in elevelDB 1.1.1 which I fixed by fetching the current template files.

Riak is now built but gives me a segmentation fault.

**Comment by ixmatus** [comment]
What do you need Riak for on Raspberry Pi? I spent some time working on
eleveldb + basho's leveldb to cross compile and run on ARM (not for the Pi
but our own custom product) but Matthew's customizations to leveldb are
significant and specific to 64 but archs. I backported the data types and
solved compiler warnings but leveldb continued to segfault. I boiled it
down to the memory synchronization primops but decided I didn't feel
comfortable rolling back all of that work on leveldb (which is tightly
coupled to eleveldb) when the segfault takes out the entire vm.

I instead decided (with a recommendation from @sargun) to use the plumtree
project. It's derived from Riak Core, is a K/V store, is network efficient
(there is no ring, all state is replicated and stored locally on each node)
and not designed to be a "database" but more of a state replication tool.

It did use the latest versions of eleveldb and leveldb but _only_ for the
hashtree module. I moved the hashtree module away from Basho's eleveldb +
leveldb and instead used lets which is an API compatible ETS/DETS behavior
and interface with pluggable storage backends.

I've successfully cross-compiled vanilla google leveldb and ran all tests
without segfaults so I cross-compiled lets and replaced the usage of
eleveldb in the hashtree module with lets. So far this is working extremely
well for us. All of my work is done in forks so you can use it or fork my
fork if you like.

https://github.com/plumlife/plumtree/tree/ARM32-lets

**Comment by ixmatus** [comment]
One more clarification: lets has leveldb as an option for storage, hence my
comments about cross-compiling it. There are _many_ reasons to use leveldb
over DETS even when you're just replicating some small state, our backing
stores are SDCards and the guarantees leveldb can give us are much stronger
than DETS. Although you can technically tell lets that you want to use DETS
instead of leveldb if you wanted to keep it all pure Erlang.
ᐧ

On Sun, Aug 2, 2015 at 2:34 PM, Parnell Springmeyer <
parnell@digitalmentat.com> wrote:

> What do you need Riak for on Raspberry Pi? I spent some time working on
> eleveldb + basho's leveldb to cross compile and run on ARM (not for the Pi
> but our own custom product) but Matthew's customizations to leveldb are
> significant and specific to 64 but archs. I backported the data types and
> solved compiler warnings but leveldb continued to segfault. I boiled it
> down to the memory synchronization primops but decided I didn't feel
> comfortable rolling back all of that work on leveldb (which is tightly
> coupled to eleveldb) when the segfault takes out the entire vm.
> 
> I instead decided (with a recommendation from @sargun) to use the plumtree
> project. It's derived from Riak Core, is a K/V store, is network efficient
> (there is no ring, all state is replicated and stored locally on each node)
> and not designed to be a "database" but more of a state replication tool.
> 
> It did use the latest versions of eleveldb and leveldb but _only_ for the
> hashtree module. I moved the hashtree module away from Basho's eleveldb +
> leveldb and instead used lets which is an API compatible ETS/DETS behavior
> and interface with pluggable storage backends.
> 
> I've successfully cross-compiled vanilla google leveldb and ran all tests
> without segfaults so I cross-compiled lets and replaced the usage of
> eleveldb in the hashtree module with lets. So far this is working extremely
> well for us. All of my work is done in forks so you can use it or fork my
> fork if you like.
> 
> https://github.com/plumlife/plumtree/tree/ARM32-lets
> On Aug 2, 2015 10:05 AM, "NoKriK" notifications@github.com wrote:
> 
> > The issue at the relbar generate step is due to missing configuration
> > template files in elevelDB 1.1.1 which I fixed by fetching the current
> > template files.
> > This is actually the following issue: basho/riak#551
> > https://github.com/basho/riak/issues/551
> > 
> > Riak is now built but gives me a segmentation fault.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/basho/eleveldb/issues/106#issuecomment-127034498.
> > 
> > ᐧ

## 

Parnell Springmeyer
parnell@digitalmentat.com | digitalmentat.com | 0xDCCF89258EAD874A
http://pgp.mit.edu/pks/lookup?op=get&search=0xDCCF89258EAD874A

**Comment by NoKriK** [comment]
Thanks @ixmatus for sharing your experience.

I'm not trying to run Riak on a Pi, I'm wanting to run it on the [Scaleway Cloud](https://www.scaleway.com/) which is arm based.
I intended to test how it performs on a 5 node cluster and to scale this cluster up to 32 nodes.
I would also have tested how Riak S2 behave on these nodes.

I wanted to create an InstantApp on the [Scaleway ImageHub](https://www.scaleway.com/imagehub/) but as 32 bits is not supported anymore, this seems to be hard to achieve.

**Comment by NoKriK** [comment]
Correctly testing this pull request https://github.com/basho/eleveldb/pull/144 and this seems to fix the issue!
