### ISSUE TITLE
enif_send: env==NULL on non-SMP VM

### ISSUE THREAD

**Issue by carlhoerberg** [basho/eleveldb#120]
When loading eleveldb on a single core ubuntu 14.04 machine with erlang 17.1 it crashes with 

```
enif_send: env==NULL on non-SMP VM
Aborted (core dumped)
```

Any ideas?

**Comment by jonmeredith** [comment]
eleveldb uses an async thread pool and requires calling enif_send from non-scheduler threads. Unfortunately that is not possible on the non-SMP emulator.

http://www.erlang.org/doc/man/erl_nif.html#enif_send

If on a uniprocessor system, start erlang with

```
erl -smp enable
```

**Comment by carlhoerberg** [comment]
Great, thanks!
