### ISSUE TITLE
Error in using eleveldb

### ISSUE THREAD

**Issue by Dryymoon** [basho/eleveldb#123]
(root@s1.dc3)1> eleveldb:open("my",[]).

=ERROR REPORT==== 5-Aug-2014::22:38:38 ===
The on_load function for module eleveldb returned {error,
                                                   {load_failed,
                                                    "Failed to load NIF library: '/usr/ROOT_NEW/APPLICATION/deps/eleveldb/priv/eleveldb.so: Undefined symbol \"__sync_sub_and_fetch_8\"'"}}
*\* exception error: undefined function eleveldb:open/2
(root@s1.dc3)2> eleveldb:open("my",[{create_if_missing, true}]).

=ERROR REPORT==== 5-Aug-2014::22:39:27 ===
The on_load function for module eleveldb returned {error,
                                                   {load_failed,
                                                    "Failed to load NIF library: '/usr/ROOT_NEW/APPLICATION/deps/eleveldb/priv/eleveldb.so: Undefined symbol \"__sync_sub_and_fetch_8\"'"}}
*\* exception error: undefined function eleveldb:open/2
(root@s1.dc3)3> eleveldb:init().

=ERROR REPORT==== 5-Aug-2014::22:43:56 ===
The on_load function for module eleveldb returned {error,
                                                   {load_failed,
                                                    "Failed to load NIF library: '/usr/ROOT_NEW/APPLICATION/deps/eleveldb/priv/eleveldb.so: Undefined symbol \"__sync_sub_and_fetch_8\"'"}}
*\* exception error: undefined function eleveldb:init/0

**Comment by seancribbs** [comment]
The NIF library clearly didn't build correctly or is not in that location. What platform are you on?

**Comment by Dryymoon** [comment]
Iwas compiled eleveldb branch 2.0,
I check the location "/usr/ROOT_NEW/APPLICATION/deps/eleveldb/priv/eleveldb.so" - file exist.
Today i try compile eleveldb branch develop (Os Freebsd 9.2, OTP 17.1, latest rebar), and i got en error:

...
`
....
==> eleveldb (compile)
....
ar -rs libleveldb.a db/builder.o db/c.o db/db_impl.o db/db_iter.o db/dbformat.o db/filename.o db/log_reader.o db/log_writer.o db/memtable.o db/repair.o db/table_cache.o db/version_edit.o db/version_set.o db/write_batch.o table/block.o table/block_builder.o table/filter_block.o table/format.o table/iterator.o table/merger.o table/table.o table/table_builder.o table/two_level_iterator.o util/arena.o util/bloom.o util/bloom2.o util/cache.o util/cache2.o util/coding.o util/comparator.o util/crc32c.o util/db_list.o util/env.o util/env_posix.o util/filter_policy.o util/flexcache.o util/hash.o util/histogram.o util/hot_threads.o util/logging.o util/murmurhash.o util/options.o util/perf_count.o util/status.o util/throttle.o port/port_posix.o
ar: warning: creating libleveldb.a
gmake[1]: Leaving directory`/usr/FROBILL/ROOT_NEW/APPLICATION/deps/eleveldb/c_src/leveldb'
Compiled src/eleveldb_bump.erl
Compiled src/eleveldb.erl
Compiling /usr/FROBILL/ROOT_NEW/APPLICATION/deps/eleveldb/c_src/eleveldb.cc
/usr/FROBILL/ROOT_NEW/APPLICATION/deps/eleveldb/c_src/eleveldb.cc: In function 'ERL_NIF_TERM parse_init_option(ErlNifEnv_, ERL_NIF_TERM, EleveldbOptions&)':
/usr/FROBILL/ROOT_NEW/APPLICATION/deps/eleveldb/c_src/eleveldb.cc:244: error: invalid conversion from 'size_t_' to 'long unsigned int_'
/usr/FROBILL/ROOT_NEW/APPLICATION/deps/eleveldb/c_src/eleveldb.cc:244: error:   initializing argument 3 of 'int enif_get_ulong(ErlNifEnv_, ERL_NIF_TERM, long unsigned int_)'
/usr/FROBILL/ROOT_NEW/APPLICATION/deps/eleveldb/c_src/eleveldb.cc: In function 'ERL_NIF_TERM parse_open_option(ErlNifEnv_, ERL_NIF_TERM, leveldb::Options&)':
/usr/FROBILL/ROOT_NEW/APPLICATION/deps/eleveldb/c_src/eleveldb.cc:332: error: invalid conversion from 'size_t_' to 'long unsigned int_'
/usr/FROBILL/ROOT_NEW/APPLICATION/deps/eleveldb/c_src/eleveldb.cc:332: error:   initializing argument 3 of 'int enif_get_ulong(ErlNifEnv_, ERL_NIF_TERM, long unsigned int_)'
ERROR: compile failed while processing /usr/FROBILL/ROOT_NEW/APPLICATION/deps/eleveldb: rebar_abort
gmake: **\* [deps] Error 1
root@s1:/usr/FROBILL/ROOT_NEW/APPLICATION #
`

**Comment by Dryymoon** [comment]
i tryed build eleveldb, branch - develop on FreeBSD 9.2 64bit, all builded clean, but i have an errorin runing:
Eshell V6.0  (abort with ^G)
(root@s2.dc3ua.frogille.com)1> eleveldb:open("my",[]).
*\* exception error: undefined function eleveldb:open/2
(root@s2.dc3ua.frogille.com)2>
=ERROR REPORT==== 16-Aug-2014::20:55:31 ===
The on_load function for module eleveldb returned {error,
                                                   {load_failed,
                                                    "Failed to load NIF library: '/usr/FROBILL/ROOT_NEW/APPLICATION/deps/eleveldb/priv/eleveldb.so: unsupported file layout'"}}

FILE /usr/FROBILL/ROOT_NEW/APPLICATION/deps/eleveldb/priv/eleveldb.so Exist.

**Comment by pbeeler** [comment]
I had a simular problem with a android app and size_t.  I solved it by converting size_t to uint_32_t, since it is a 32bit program, but I'm using a arm64 bit compiler to compile it.

Have a look here:
https://github.com/SaberMod/android_packages_apps_DSPManager/commit/3d358a4f494e61ccddfee50d01cb0c4e1ef0638c

in your case you probably need to convert it for 64bit.
