### ISSUE TITLE
Minimize memory usage [JIRA: RIAK-2167]

### ISSUE THREAD

**Issue by carlhoerberg** [basho/eleveldb#127]
We're trying to use eleveldb as a backend to RabbitMQ's message index and are seeing some really promising early results! It allows us to have virtually infinitely long queues (by default rabbitmq keeps its message index in-memory which limits the queue length to a few million msgs on normal machines). 

But we think that the default configuration might not be ideal for our use case. We want to balance the memory usage between the message storage and the index. We also only have two databases open ever. The index is rebuilt if RabbitMQ wasn't shutdown cleanly so we can skip all verifications etc. What nobs do think is worth fiddling with?

**Comment by michaelklishin** [comment]
Any comments on this? We are interested in using eleveldb as a message index option for RabbitMQ.

**Comment by cmeiklejohn** [comment]
I'm not a LevelDB expert, so I can't advise you of the best configurations myself, but I can point you in the direction of our in-depth turning documentation, which might provide some additional information of use: http://docs.basho.com/riak/latest/ops/advanced/backends/leveldb/

**Comment by engelsanchez** [comment]
Chris is right: it's very useful to see the knobs that are exposed through Riak. Latest versions of eleveldb, the way we use them, mostly only require a single parameter: the amount of memory it is allowed to use for its combined buffers (shared by all instances) as an absolute number or percentage of memory. That should be easy enough to try: https://github.com/basho/eleveldb/blob/develop/src/eleveldb.erl#L95. By using that, you don't have to tweak the buffers per instance. You can still do that the old fashioned way if you prefer by passing the write buffer size.

Another thing that is done automatically now is sizing the blocks in the SST files. Bigger blocks result in smaller memory footprint as the metadata kept in memory is smaller, but also may increase latency as more scanning may need to done to find a particular entry.  The code tries to balance that and find the optimal size: https://github.com/basho/leveldb/wiki/mv-dynamic-block-size#block-size-algorithm.  If the algorithm doesn't seem to work for you, you can still try the old fashioned way and specify the  sst block size.

As you tweak those, monitor Leveldb memory footprint and I/O usage over a long enough time for compactions to have an effect (block sizing only affects new files, so you may need a whole compaction cycle before you see the effect). That is probably days and not hours.

**Comment by matthewvon** [comment]
Is this issue "closed", or do questions remain?  @michaelklishin and @carlhoerberg 

The basic memory model is 300Mbytes per database for "good" performance.  If you have a ton of memory, there is a sweet spot at 2.5Gbytes per database for heavy users.
