### ISSUE TITLE
Thread pool synchronizing problem? [JIRA: RIAK-1912]

### ISSUE THREAD

**Issue by agilesoftware** [basho/eleveldb#141]
in, `submit(eleveldb_thread_pool::submit)` :

```
 else if (!FindWaitingThread(item))
         {
             // no waiting threads, put on backlog queue
             lock();
             eleveldb::inc_and_fetch(&work_queue_atomic);
             work_queue.push_back(item);
             unlock();

             // to address race condition, thread might be waiting now
             FindWaitingThread(NULL);

             perf()->Inc(leveldb::ePerfElevelQueued);
             ret_flag=true;
         }   // if 
```

It first check if there's an waiting thread to submit directly(and pthread_cond_broadcast in `FindWaitingThread`), or it will add `item` to work_queue.

On the other hand, in eleveldb_write_thread_worker(threading.cc), when a working thread cannot find a work item, it will wait on its condition variable.

```
            pthread_mutex_lock(&tdata.m_Mutex);
            tdata.m_DirectWork=NULL; // safety

            // only wait if we are really sure no work pending
            if (0==h.work_queue_atomic)
        {
                // yes, thread going to wait. set available now.
            tdata.m_Available=1;
                pthread_cond_wait(&tdata.m_Condition, &tdata.m_Mutex);
        }    // if

            tdata.m_Available=0;    // safety
            submission=(eleveldb::WorkTask *)tdata.m_DirectWork; // NULL is valid
            tdata.m_DirectWork=NULL;// safety

            pthread_mutex_unlock(&tdata.m_Mutex);
```

after checking the working queue is empty(work_queue_atomic==0), it sets its available to 1. 

The problem is, if an working thread has checked that the working queue is empty , and before it's setting available, `submit` maybe cannot find a waiting thread, add an item to queue. At this moment, the working thread starts waiting, then this working thread will wait forever.(The second `FindWaitingThread(NULL)` doesn't help, it also maybe executed in this period). In fact, if the working thread has setting its available, and before waiting on  its condition, and `submit`  set its `direct_work`, broadcast the condition variable, and the working thread wait, it will wait forever too.

**Comment by Basho-JIRA** [comment]
Is this a question based upon code review or an experienced condition? 

**_[posted via JIRA by Matthew Von-Maszewski]**_

**Comment by Basho-JIRA** [comment]
This condition was addressed in the leveldb version of this code via an extra thread that is based upon sem_post().  Said extra thread logic could be back ported. 

**_[posted via JIRA by Matthew Von-Maszewski]**_

**Comment by agilesoftware** [comment]
It is based on code review, but when I add a `sleep` before waiting, it happens.

Where is the leveldb version? Thanks.

**Comment by Basho-JIRA** [comment]
leveldb/hot_threads.cc http://thottle.cc/ contains the leveldb updated version.

**_[posted via JIRA by Matthew Von-Maszewski]**_

**Comment by jonmeredith** [comment]
@agilesoftware did you get a chance to review the code @matthewvon pointed to?

**Comment by agilesoftware** [comment]
@jonmeredith Because of network problems, I can't get the code  @matthewvon provided, but I did checkout the Basho modified version from github. It seems this issue has been solved by hot_thread.cc, when an item is added to the queue, QueueThread will certainly  get the item from the queue if no other working thread is available.(The last part of my previous post is error, it is protected by a working thread's mutex.+﹏+).

**Comment by matthewvon** [comment]
@agilesoftware ... Paul Place is actively working to replace the threading.cc/.hpp code.  The result will be the use of leveldb's hot thread classes from within the leveldb library, i.e. NOT copying code from leveldb into eleveldb.

P.S.  This was good work on your part.  We are hiring for Erlang, C/C++, Java, and other languages.  Just thought you should know.
