### ISSUE TITLE
number of file handles used [JIRA: RIAK-2209]

### ISSUE THREAD

**Issue by videlalvaro** [basho/eleveldb#151]
Is it possible to obtain the number of file handles used by the database?

**Comment by matthewvon** [comment]
Basho's leveldb tracks its open files via performance counters.  The key counters are ROFileOpen, ROFileClose, RWFileOpen, and RWFileClose.  These counters are always incrementing.  To get a current "open" count use this formula current_open=(ROFileOpen+RWFileOpen)-(ROFileClose+RWFileClose).

There are several ways to access the counters:
- leveldb has an API call leveldb::DB::GetProperty() where you give "leveldb.ROFileOpen" as the property.
- eleveldb has an API call eleveldb::status() where you give a database reference and "leveldb.ROFileOpen".
- there is a perf_dump tool that you can build to retrieve the counters from a command line.  Details are here:  https://github.com/basho/leveldb/wiki/perf_dump

The Linux operating system also supports finding database file handles.  The following command lists all files open by Riak / Erlang:

ls -la /proc/$(pgrep beam)/fd

You can use "grep" and "wc -l" to get counts of specific databases.

**Comment by videlalvaro** [comment]
I know about asking the OS to report on file handles open by a certain process. The thing is if we want to integrate this into RabbitMQ, we need to have:

a) a portable solution.
b) this information should be accessible by RabbitMQ itself, since the broker has it's own way of handling open file handles for different monitoring purposes.

**Comment by matthewvon** [comment]
OS report was 4th way.  Do one of the other 3 satisfy?

**Comment by videlalvaro** [comment]
I'll take a look at the other options and see how they work for us. Thanks.
