### ISSUE TITLE
Compilation failed eleveldb.cc in RHEL 6.5 32 bit OS [JIRA: RIAK-2627]

### ISSUE THREAD

**Issue by get4gopim** [basho/eleveldb#197]
I am trying to build riak-2.1.4 on RHEL 6.5 32 bit OS. I have installed the erlang by following the steps mentioned in the below riak link:
http://docs.basho.com/riak/kv/2.1.4/setup/installing/source/erlang/#installing-on-rhel-centos

I am using the right version of Erlang, which is mentioned in Riak installation page.

`[root@server123 riak-2.1.4]# erl --version
Erlang R16B02_basho8 (erts-5.10.3) [source] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V5.10.3  (abort with ^G)`

I have tried using different version of RHEL 6 32, but all are failing.

Error when I do: _make rel_

`gmake[1]: Leaving directory`/opt/Avaya/releases/basho/riak-2.1.4/deps/eleveldb/c_src/leveldb'
Compiling /opt/Avaya/releases/basho/riak-2.1.4/deps/eleveldb/c_src/eleveldb.cc
/opt/Avaya/releases/basho/riak-2.1.4/deps/eleveldb/c_src/eleveldb.cc: In function ‘ERL_NIF_TERM parse_init_option(ErlNifEnv_, ERL_NIF_TERM, EleveldbOptions&)’:
/opt/Avaya/releases/basho/riak-2.1.4/deps/eleveldb/c_src/eleveldb.cc:246: error: invalid conversion from ‘size_t_’ to ‘long unsigned int_’
/opt/Avaya/releases/basho/riak-2.1.4/deps/eleveldb/c_src/eleveldb.cc:246: error:   initializing argument 3 of ‘int enif_get_ulong(ErlNifEnv_, ERL_NIF_TERM, long unsigned int_)’
/opt/Avaya/releases/basho/riak-2.1.4/deps/eleveldb/c_src/eleveldb.cc: In function ‘ERL_NIF_TERM parse_open_option(ErlNifEnv_, ERL_NIF_TERM, leveldb::Options&)’:
/opt/Avaya/releases/basho/riak-2.1.4/deps/eleveldb/c_src/eleveldb.cc:334: error: invalid conversion from ‘size_t_’ to ‘long unsigned int_’
/opt/Avaya/releases/basho/riak-2.1.4/deps/eleveldb/c_src/eleveldb.cc:334: error:   initializing argument 3 of ‘int enif_get_ulong(ErlNifEnv_, ERL_NIF_TERM, long unsigned int_)’
/opt/Avaya/releases/basho/riak-2.1.4/deps/eleveldb/c_src/eleveldb.cc: In function ‘ERL_NIF_TERM eleveldb::async_open(ErlNifEnv_, int, const ERL_NIF_TERM_)’:
/opt/Avaya/releases/basho/riak-2.1.4/deps/eleveldb/c_src/eleveldb.cc:593: warning: integer overflow in expression
ERROR: compile failed while processing /opt/Avaya/releases/basho/riak-2.1.4/deps/eleveldb: rebar_abort
make: **\* [compile] Error 1`

**Comment by matthewvon** [comment]
Basho dropped all 32 bit support for Riak (and therefore eleveldb) 3, maybe 4, years ago.  I have not performed a 32bit compile since then.  That said, this is something easy.

The errors you are seeing are from Erlang's erl_nif.h being slightly inconsistent between 32 bit and 64 bit options and the size_t type.  You can address lines 246 and 334 by either changing memory_sz to unsigned long or changing the call to enif_get_int().

Line 593 could likely be addressed by changing the "L" suffix to "ULL" or "LL".

**Comment by get4gopim** [comment]
Thank you. Better we can stop using Riak installation in 32 bit OS.
