### ISSUE TITLE
compaction spins on corrupt sst

### ISSUE THREAD

**Issue by matthewvon** [basho/eleveldb#23]

**Comment by jonmeredith** [comment]
See also https://help.basho.com/tickets/1224

**Comment by matthewvon** [comment]
This is a temporary hack.  This change causes the code to skip over a corrupted block.  Previous logic would report the error to upper layers which would:

a. cause compaction to begin looping infinitely, or
b. cause repair to throw away an entire file of key/values instead of just the single corrupted one.

Bad news is that the layer of the fix does NOT have access to logging.  This skipping is going to happen silently for a while.  Not happy about that at all.

branch is platform23-skip-corruption

**Comment by jonmeredith** [comment]
Is this resolved by basho/leveldb#6 ?

**Comment by matthewvon** [comment]
This is a dead branch.  The fix here has been superseded by mv-badblock-recovery in leveldb.  Not shire what to do about this ... close it?

**Comment by jonmeredith** [comment]
Yes, just click 'comment and close' on github.

On Sun, Jun 3, 2012 at 9:52 PM, matthewvon <
reply@reply.github.com
