### ISSUE TITLE
Asynchronous implementation of iterator_move () was slower.

### ISSUE THREAD

**Issue by dmelnik** [basho/eleveldb#46]
After the implementation of the iterator_move() method using  thread_pool reading values from ​​leveldb was about 10 times slower. In synchronous variant it was approximately 300,000 records per second, and in asynchronous - 30 000. Maybe you should add to the API method for get a list of records at once, not to pick one by one? This should solve the problem.

**Comment by matthewvon** [comment]
Please retest.  That code took a major performance hit when moved from direct call to async call (done to make Erlang happy, not my choosing).  It has been reworked extensively.

**Comment by dmelnik** [comment]
Checked on version eleveldb 1.2.3.
Yes, it was faster - about 70,000 records per second instead of 30,000. But it is still very far behind 300, 000 records per second in synchronous mode (version 1.2.2p5).
I understand that to keep asking stupid questions, but why not implement queue with asynchronous calls with bulk of records in addition (or instead of) to the single calls for each record? After all, it should speed up RIAK map/reduce?

**Comment by seancribbs** [comment]
@dmelnik Synchronous NIF calls occur on the scheduler thread. Calls that spend more than ~1ms to complete have a tendency to skew the scheduler/work-stealing algorithm, causing highly loaded nodes to have severely imbalanced run queues. When used in the async fashion, very little time is spent in the NIF before work is handed to a background thread. This ensures that the work done by the NIF does not block the scheduler while waiting for IO, meaning that work can be rebalanced among the schedulers/cores and parallelism is increased.

**Comment by matthewvon** [comment]
You are welcome to try these two branches: jdm-batch-and-prefetch-fold and jdm-batch-and-prefetch-fold-newpool

We tried many different technologies in hopes of overcoming the performance penalty of using async operations.  The above branches implement exactly what you describe.  We did not see significant performance improvement.

**Comment by matthewvon** [comment]
Two notes:  
1.  We measure performance using the entire Riak stack.  You might achieve different results, especially with the two branches above, if you are utilizing eleveldb outside of Riak.
2.  If you are using Riak 1.3.0, please test with active anti-entropy disabled.  Add the following line to the "riak_kv" section of your app.config file:

{anti_entropy, {off, []}},

**Comment by matthewvon** [comment]
@dmelnik Where are you on this issue?  We have had code performance improvements relative to iterator_move() (in the leveldb layer).  Do you have a test script for your 300,000 records per second benchmark that can be shared?

I know, it has taken MONTHS to get back to this issue.  My apologies.

**Comment by dmelnik** [comment]
I was very sorry. I tried specified brunches, but did not get the desired performance. I thought I had written the answer, but it turned out that it is not.

The other day I tested and compared the performance on eleveldb versions 1.2.2p5 and 1.4.1 (but now on a new server, unfortunately)
In one instance leveldb been downloaded 100 million records of 50 bytes + 10 bytes per key.
Entries were read by a single thread with a call eleveldb: iterator_move (Itr, KeyStart), then loops eleveldb: iterator_move (Itr, next) for a minute.

results:
Version 1.2.2p5 = 1216885 req / sec
Version 1.4.1 = 1227540 req / sec

It turns out that the asynchronous version 1.4.1 eleveldb: iterator_move (Itr, next) works similarly to the speed synchronous 1.2.2.
Excellent!

Provide a test script is difficult because actually I'm testing a simple erlang - server with eleveldb with basho_bench.

**Comment by matthewvon** [comment]
If 1.4.1 is faster for you, then you will probably benefit further by the +S changes discussed here:

https://github.com/basho/leveldb/wiki/riak-tuning-1

1.4.1 iterators are faster due to a change in the leveldb code.  The iterators are still running through the asynchronous interface.  The above tuning discussion may give you a further iterator performance boost.  Improvement varies by physical equipment and workload.
