### ISSUE TITLE
Fix build on OpenSUSE 64bit

### ISSUE THREAD

**Issue by runesl** [basho/eleveldb#64]
In OpenSUSE 64 bit libsnappy is built into "c_src/system/lib64/" but the build proces later looks for it in "c_src/system/lib/". This breaks the build.

The problem propagates downstream to the downloadable Riak 1.4.0 and all previous releases, which is quite bad as no prebuilds of OpenSUSE 64bit are provided by basho or the OpenSUSE package maintainers, so the only way to install riak is currently hacking the installation scripts.

The problem can be fixed by either forcing libsnappy to be built into c_src/system/lib/ or by fixing the hardcoded references to "/system/lib/". "The latter is done by changing the hardcoded references to "/system/lib" from "c_src/build_deps.sh" and "rebar.config". Changing "lib" to "lib64" in these two files fixes the build.

**Comment by jaredmorrow** [comment]
That is unusual because looking at snappy's configure script, it defaults to installing to PREFIX/lib.  I will specify a --libdir to be sure that it is forceful in where it installs.  Sorry for the trouble.

**Comment by jaredmorrow** [comment]
@rsltrifork can you try out https://github.com/basho/eleveldb/pull/70 on OpenSUSE and let me know if it fixes your issue?

**Comment by matthewvon** [comment]
@rsltrifork can you confirm/deny this issue is resolved?

**Comment by runesl** [comment]
The patch seems to work. :-) I can now build eleveldb on openSUSE 12.3 x86_64.
