### ISSUE TITLE
Can I use elevelDb if I am not using riak?

### ISSUE THREAD

**Issue by ghost** [basho/eleveldb#94]
It is not clear to me from the readme if this is meant to be used as a riak backend only. Can it be used as an embedded database library like say [levelup](https://github.com/rvagg/node-levelup). 

Thanks.

**Comment by seancribbs** [comment]
Yes. Some settings tend to be Riak-specific, but you can definitely use this independently of Riak.

**Comment by ghost** [comment]
Thanks for the answer Sean . I have got one more question. Is there any documentation of the api apart from unit tests.
