### ISSUE TITLE
Iterator move prev unsupported?

### ISSUE THREAD

**Issue by jonasrichard** [basho/eleveldb#99]
As I noticed every type of iterator move works except prev. I got a bad argument exception anytime I call `eleveldb:iterator_move(Iter, prev)`.
I saw in the source this message:

``` c
    // prefetch logic broke PREV and not fixing for Riak
    if(NULL==itr_ptr.get()
       || (enif_is_atom(env, action_or_target) && ATOM_PREV==action_or_target))
        return enif_make_badarg(env);
```

Is there any change that somewhere in the near future it is fixed?

**Comment by matthewvon** [comment]
try "develop" branch.

**Comment by matthewvon** [comment]
Have you confirmed your bug is fixed or not fixed by the "develop" branch of eleveldb?

**Comment by jonasrichard** [comment]
It works on the develop branch as expected. I am closing this issue.
